extends Node



const GROUP_NAME_HITBOXES = "HitBoxes"
const GROUP_NAME_HURTBOXES = "HurtBoxes"

const DATA_LABEL_BURGERS = "HAMBURGERS"
const DATA_LABEL_HEALTH = "HEALTH"
const DATA_LABEL_POINTS = "POINTS"

const PlayerData : Dictionary =  {
	DATA_LABEL_BURGERS: 0,
	DATA_LABEL_HEALTH: 3,
	DATA_LABEL_POINTS: 0
}


const PICKUP_NAME_BURGER := 'BURGER'
const PICKUP_NAME_HEALTH := 'HEALTH'


const SOUND_NAME_JUMP := "JUMP"
const SOUND_NAME_COLLECT := "COLLECT"
const SOUND_NAME_DEFEAT := "DEFEAT"
const SOUND_NAME_UMBRELLA_OPEN := "UMBRELLA_OPEN"
const SOUND_NAME_UMBRELLA_CLOSE := "UMBRELLA_CLOSE"
const SOUND_NAME_TAKE_DAMAGE := "TAKE_DAMAGE"
const SOUND_NAME_HEAL := "HEAL"
const SOUND_NAME_ENEMY_DEFEATED := "ENEMY_DEFEATED"
const SOUND_NAME_LOOSE_ITEM := "LOOSE_ITEM"
const SOUND_NAME_BUMP := "BUMP"
const SOUND_NAME_GROW := "GROW"
const SOUND_NAME_FEED := "FEED"
const SOUND_NAME_STEP := "STEP"
